graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Superfluid Checkout - Checkout Widget V1 - Components]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 3 [Checkout Widget V1]
      style 3 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      subgraph group1 [Commands]
        style group1 fill:#ffffff,stroke:#cccccc,color:#cccccc,stroke-dasharray:5

        12["<div style='font-weight: bold'>Wrap Super Tokens Command</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 12 fill:#dddddd,stroke:#9a9a9a,color:#000000
        15["<div style='font-weight: bold'>Subscribe Command</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 15 fill:#dddddd,stroke:#9a9a9a,color:#000000
        9["<div style='font-weight: bold'>Enable Auto-Wrap Command</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 9 fill:#dddddd,stroke:#9a9a9a,color:#000000
      end

      subgraph group2 [On-Chain Transactions]
        style group2 fill:#ffffff,stroke:#cccccc,color:#cccccc,stroke-dasharray:5

        4["<div style='font-weight: bold'>Authorize Auto-Wrap</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 4 fill:#dddddd,stroke:#9a9a9a,color:#000000
        5["<div style='font-weight: bold'>Enable Auto-Wrap</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 5 fill:#dddddd,stroke:#9a9a9a,color:#000000
        6["<div style='font-weight: bold'>Authorize Superfluid to Wrap Tokens</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 6 fill:#dddddd,stroke:#9a9a9a,color:#000000
        7["<div style='font-weight: bold'>Upgrade to Super Token</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 7 fill:#dddddd,stroke:#9a9a9a,color:#000000
        8["<div style='font-weight: bold'>Create Flow</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 8 fill:#dddddd,stroke:#9a9a9a,color:#000000
      end

      17["<div style='font-weight: bold'>Checkout Form</div><div style='font-size: 70%; margin-top: 0px'>[Component: wagmi, react-hook-form, Zod]</div><div style='font-size: 80%; margin-top:10px'>The form with inputs that the<br />user fills out.</div>"]
      style 17 fill:#dddddd,stroke:#9a9a9a,color:#000000
      21["<div style='font-weight: bold'>Product Info</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Product details, including<br />payment options (token &<br />network & flow rate)</div>"]
      style 21 fill:#dddddd,stroke:#9a9a9a,color:#000000
      23["<div style='font-weight: bold'>Token List</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>The display info for the<br />tokens that are set up as<br />payment options.</div>"]
      style 23 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

    9-. "<div>Produces</div><div style='font-size: 70%'></div>" .->4
    9-. "<div>Produces</div><div style='font-size: 70%'></div>" .->5
    12-. "<div>Produces</div><div style='font-size: 70%'></div>" .->6
    12-. "<div>Produces</div><div style='font-size: 70%'></div>" .->7
    15-. "<div>Produces</div><div style='font-size: 70%'></div>" .->8
    17-. "<div>Produces</div><div style='font-size: 70%'></div>" .->9
    17-. "<div>Produces</div><div style='font-size: 70%'></div>" .->12
    17-. "<div>Produces</div><div style='font-size: 70%'></div>" .->15
    21-. "<div>Input of</div><div style='font-size: 70%'></div>" .->17
    23-. "<div>Input of</div><div style='font-size: 70%'></div>" .->17
  end