graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Checkout Storage System - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 24 [Checkout Storage System]
      style 24 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      25["<div style='font-weight: bold'>Checkout Storage API</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Something to hold the<br />checkout inputs.</div>"]
      style 25 fill:#dddddd,stroke:#9a9a9a,color:#000000
      26["<div style='font-weight: bold'>Checkout IPFS</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Decentralized storage.</div>"]
      style 26 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end