graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Checkout Storage System - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 25 [Checkout Storage System]
      style 25 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      26("<div style='font-weight: bold'>Checkout Storage API</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>An API to store and retrieve<br />checkout configurations<br />(product info & payment<br />options).</div>")
      style 26 fill:#dddddd,stroke:#9a9a9a,color:#000000
      27("<div style='font-weight: bold'>Checkout IPFS</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Decentralized storage.</div>")
      style 27 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end