graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Superfluid User System - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    44["<div style='font-weight: bold'>Web3 User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div>"]
    style 44 fill:#976440,stroke:#69462c,color:#ffffff
    1["<div style='font-weight: bold'>Checkout Customer System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 1 fill:#dddddd,stroke:#9a9a9a,color:#000000

    subgraph 32 [Superfluid User System]
      style 32 fill:#ffffff,stroke:#147c1b,color:#147c1b

      33["<div style='font-weight: bold'>Superfluid Dashboard</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>The UI to see token balances<br />and flows.</div>"]
      style 33 fill:#dddddd,stroke:#9a9a9a,color:#000000
      38["<div style='font-weight: bold'>Superfluid Console</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>The UI view Superfluid<br />Protocol from bird's eye<br />view.</div>"]
      style 38 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

    33-. "<div>Can contain a generic<br />'hosted' version</div><div style='font-size: 70%'></div>" .->1
    44-. "<div>Uses to manage token balances</div><div style='font-size: 70%'></div>" .->33
    44-. "<div>Uses to make payment</div><div style='font-size: 70%'></div>" .->1
  end