graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Checkout Storage System - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 32 [Checkout Storage System]
      style 32 fill:#ffffff,stroke:#295176,color:#295176

      33("<div style='font-weight: bold'>Checkout Storage API</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>An API to store and retrieve<br />checkout configurations<br />(product info & payment<br />options).</div>")
      style 33 fill:#3b75a9,stroke:#295176,color:#ffffff
      34("<div style='font-weight: bold'>Checkout IPFS</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Decentralized storage.</div>")
      style 34 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end