graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Checkout Merchant System - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 37 [Checkout Merchant System]
      style 37 fill:#ffffff,stroke:#f8c806,color:#f8c806

      38["<div style='font-weight: bold'>Checkout Merchant Dashboard</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>The one aggregating interface<br />everything a merchant could<br />need.</div>"]
      style 38 fill:#3b75a9,stroke:#295176,color:#ffffff
      39("<div style='font-weight: bold'>Self-hostable Checkout Storage</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>A self-hostable centralized<br />storage mechanism. Can hold<br />personal information if<br />properly communicated.</div>")
      style 39 fill:#3b75a9,stroke:#295176,color:#ffffff
    end

  end