graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Superfluid User Products - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    3("<div style='font-weight: bold'>Checkout Widget System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>The main customer facing part<br />of the Checkout system.</div>")
    style 3 fill:#3b75a9,stroke:#f8c806,color:#ffffff
    65["<div style='font-weight: bold'>Web3 Consumer</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div>"]
    style 65 fill:#976440,stroke:#69462c,color:#ffffff

    subgraph 40 [Superfluid User Products]
      style 40 fill:#ffffff,stroke:#006b15,color:#006b15

      41["<div style='font-weight: bold'>Superfluid Dashboard</div><div style='font-size: 70%; margin-top: 0px'>[Container: TypeScript, Next.js (SSG), React, MUI, SDK-core, SDK-redux, Redux Toolkit (RTK), wagmi, RainbowKit, react-hook-form]</div><div style='font-size: 80%; margin-top:10px'>The web app to see token<br />balances and streams.</div>"]
      style 41 fill:#00991f,stroke:#006b15,color:#ffffff
      52["<div style='font-weight: bold'>Superfluid Console</div><div style='font-size: 70%; margin-top: 0px'>[Container: TypeScript, Next.js (SSR), React, MUI, SDK-core, SDK-redux]</div><div style='font-size: 80%; margin-top:10px'>The UI to view Superfluid<br />Protocol from bird's eye<br />view. Directed at developers.</div>"]
      style 52 fill:#00991f,stroke:#006b15,color:#ffffff
      53["<div style='font-weight: bold'>Superfluid Website</div><div style='font-size: 70%; margin-top: 0px'>[Container: TypeScript, Next.js (SSR), React, MDX, gsap (animations), Strapi]</div><div style='font-size: 80%; margin-top:10px'>The main website for<br />introducing Superfluid<br />Protocol. Mostly static<br />marketing content.</div>"]
      style 53 fill:#00991f,stroke:#006b15,color:#ffffff
    end

    41-. "<div>Might 'host' a decentralized<br />version</div><div style='font-size: 70%'></div>" .->3
    65-. "<div>Uses to view balances &<br />manage Superfluid things</div><div style='font-size: 70%'></div>" .->41
    65-. "<div>Uses to make payment with</div><div style='font-size: 70%'></div>" .->3
  end