graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Checkout Merchant System - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 32 [Checkout Merchant System]
      style 32 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      33["<div style='font-weight: bold'>Checkout Merchant Dashboard</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>The one aggregating interface<br />everything a merchant could<br />need.</div>"]
      style 33 fill:#dddddd,stroke:#9a9a9a,color:#000000
      34("<div style='font-weight: bold'>Self-hostable Checkout Storage</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>A self-hostable centralized<br />storage mechanism. Can hold<br />personal information if<br />properly communicated.</div>")
      style 34 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end