graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Checkout Widget System - Checkout Widget - Components]
    style diagram fill:#ffffff,stroke:#ffffff

    22("<div style='font-weight: bold'>Product Info</div><div style='font-size: 70%; margin-top: 0px'>[Container: Schema-validated JSON]</div><div style='font-size: 80%; margin-top:10px'>Product details, including<br />payment options (token &<br />network & flow rate)</div>")
    style 22 fill:#dddddd,stroke:#9a9a9a,color:#000000
    25("<div style='font-weight: bold'>Token List</div><div style='font-size: 70%; margin-top: 0px'>[Container: Schema-validated JSON, Uniswap's Token List standard]</div><div style='font-size: 80%; margin-top:10px'>The display info for the<br />tokens that are set up as<br />payment options.</div>")
    style 25 fill:#dddddd,stroke:#9a9a9a,color:#000000

    subgraph 4 [Checkout Widget]
      style 4 fill:#ffffff,stroke:#f8c806,color:#f8c806

      subgraph group1 [Commands]
        style group1 fill:#ffffff,stroke:#cccccc,color:#cccccc,stroke-dasharray:5

        10("<div style='font-weight: bold'>Enable Auto-Wrap Command</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 10 fill:#3399fe,stroke:#236bb1,color:#ffffff
        13("<div style='font-weight: bold'>Wrap Super Tokens Command</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 13 fill:#3399fe,stroke:#236bb1,color:#ffffff
        16("<div style='font-weight: bold'>Subscribe Command</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 16 fill:#3399fe,stroke:#236bb1,color:#ffffff
      end

      subgraph group2 [On-Chain Transactions]
        style group2 fill:#ffffff,stroke:#cccccc,color:#cccccc,stroke-dasharray:5

        5("<div style='font-weight: bold'>Authorize Auto-Wrap</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 5 fill:#dddddd,stroke:#9a9a9a,color:#000000
        6("<div style='font-weight: bold'>Enable Auto-Wrap</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 6 fill:#dddddd,stroke:#9a9a9a,color:#000000
        7("<div style='font-weight: bold'>Authorize Superfluid to Wrap Tokens</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 7 fill:#dddddd,stroke:#9a9a9a,color:#000000
        8("<div style='font-weight: bold'>Upgrade to Super Token</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 8 fill:#dddddd,stroke:#9a9a9a,color:#000000
        9("<div style='font-weight: bold'>Create Flow</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
        style 9 fill:#dddddd,stroke:#9a9a9a,color:#000000
      end

      18("<div style='font-weight: bold'>Checkout Form</div><div style='font-size: 70%; margin-top: 0px'>[Component: wagmi, react-hook-form, Zod]</div><div style='font-size: 80%; margin-top:10px'>The form with inputs that the<br />user fills out.</div>")
      style 18 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

    10-. "<div>Produces</div><div style='font-size: 70%'></div>" .->5
    10-. "<div>Produces</div><div style='font-size: 70%'></div>" .->6
    13-. "<div>Produces</div><div style='font-size: 70%'></div>" .->7
    13-. "<div>Produces</div><div style='font-size: 70%'></div>" .->8
    16-. "<div>Produces</div><div style='font-size: 70%'></div>" .->9
    18-. "<div>Produces</div><div style='font-size: 70%'></div>" .->10
    18-. "<div>Produces</div><div style='font-size: 70%'></div>" .->13
    18-. "<div>Produces</div><div style='font-size: 70%'></div>" .->16
    22-. "<div>Input of</div><div style='font-size: 70%'></div>" .->18
    25-. "<div>Input of</div><div style='font-size: 70%'></div>" .->18
  end