graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Checkout Customer System - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    44["<div style='font-weight: bold'>Web3 User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div>"]
    style 44 fill:#976440,stroke:#69462c,color:#ffffff
    39["<div style='font-weight: bold'>Web3 Stores</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 39 fill:#dddddd,stroke:#9a9a9a,color:#000000
    32["<div style='font-weight: bold'>Superfluid User System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 32 fill:#1db227,stroke:#147c1b,color:#ffffff

    subgraph 1 [Checkout Customer System]
      style 1 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      2["<div style='font-weight: bold'>Checkout Widget V1</div><div style='font-size: 70%; margin-top: 0px'>[Container: TypeScript, React, MUI, wagmi, Zod, Token List]</div><div style='font-size: 80%; margin-top:10px'>Provides a streamlined UX to<br />subscribe to the given<br />product.</div>"]
      style 2 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

    32-. "<div>Can contain a generic<br />'hosted' version</div><div style='font-size: 70%'></div>" .->2
    39-. "<div>The website that holds the<br />checkout widget(s).</div><div style='font-size: 70%'></div>" .->2
    44-. "<div>Uses to manage token balances</div><div style='font-size: 70%'></div>" .->32
    44-. "<div>Goes to subscribe to a<br />product</div><div style='font-size: 70%'></div>" .->39
    44-. "<div>Uses to make payment</div><div style='font-size: 70%'></div>" .->2
  end