export const superTokenABI = [
    {
      stateMutability: 'nonpayable',
      type: 'constructor',
      inputs: [
        { name: 'host', internalType: 'contract ISuperfluid', type: 'address' },
      ],
    },
    { type: 'error', inputs: [], name: 'SF_TOKEN_AGREEMENT_ALREADY_EXISTS' },
    { type: 'error', inputs: [], name: 'SF_TOKEN_AGREEMENT_DOES_NOT_EXIST' },
    { type: 'error', inputs: [], name: 'SF_TOKEN_BURN_INSUFFICIENT_BALANCE' },
    { type: 'error', inputs: [], name: 'SF_TOKEN_MOVE_INSUFFICIENT_BALANCE' },
    { type: 'error', inputs: [], name: 'SF_TOKEN_ONLY_HOST' },
    { type: 'error', inputs: [], name: 'SF_TOKEN_ONLY_LISTED_AGREEMENT' },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_APPROVE_FROM_ZERO_ADDRESS' },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_APPROVE_TO_ZERO_ADDRESS' },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_BURN_FROM_ZERO_ADDRESS' },
    {
      type: 'error',
      inputs: [],
      name: 'SUPER_TOKEN_CALLER_IS_NOT_OPERATOR_FOR_HOLDER',
    },
    {
      type: 'error',
      inputs: [],
      name: 'SUPER_TOKEN_INFLATIONARY_DEFLATIONARY_NOT_SUPPORTED',
    },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_MINT_TO_ZERO_ADDRESS' },
    {
      type: 'error',
      inputs: [],
      name: 'SUPER_TOKEN_NOT_ERC777_TOKENS_RECIPIENT',
    },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_NO_UNDERLYING_TOKEN' },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_ONLY_HOST' },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_ONLY_SELF' },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_TRANSFER_FROM_ZERO_ADDRESS' },
    { type: 'error', inputs: [], name: 'SUPER_TOKEN_TRANSFER_TO_ZERO_ADDRESS' },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'agreementClass',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: false },
        {
          name: 'data',
          internalType: 'bytes32[]',
          type: 'bytes32[]',
          indexed: false,
        },
      ],
      name: 'AgreementCreated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'agreementClass',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: false },
        {
          name: 'penaltyAccount',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'rewardAccount',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'rewardAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'AgreementLiquidated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'liquidatorAccount',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        {
          name: 'agreementClass',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: false },
        {
          name: 'penaltyAccount',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'bondAccount',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'rewardAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'bailoutAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'AgreementLiquidatedBy',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'agreementClass',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: false },
        {
          name: 'liquidatorAccount',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'targetAccount',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'rewardAmountReceiver',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        {
          name: 'rewardAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'targetAccountBalanceDelta',
          internalType: 'int256',
          type: 'int256',
          indexed: false,
        },
        {
          name: 'liquidationTypeData',
          internalType: 'bytes',
          type: 'bytes',
          indexed: false,
        },
      ],
      name: 'AgreementLiquidatedV2',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'agreementClass',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'slotId',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'AgreementStateUpdated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'agreementClass',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: false },
      ],
      name: 'AgreementTerminated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'agreementClass',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: false },
        {
          name: 'data',
          internalType: 'bytes32[]',
          type: 'bytes32[]',
          indexed: false,
        },
      ],
      name: 'AgreementUpdated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'owner',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'spender',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'value',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Approval',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'tokenHolder',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'AuthorizedOperator',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'bailoutAccount',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'bailoutAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Bailout',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'from', internalType: 'address', type: 'address', indexed: true },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        { name: 'data', internalType: 'bytes', type: 'bytes', indexed: false },
        {
          name: 'operatorData',
          internalType: 'bytes',
          type: 'bytes',
          indexed: false,
        },
      ],
      name: 'Burned',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'uuid',
          internalType: 'bytes32',
          type: 'bytes32',
          indexed: false,
        },
        {
          name: 'codeAddress',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'CodeUpdated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'version', internalType: 'uint8', type: 'uint8', indexed: false },
      ],
      name: 'Initialized',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'to', internalType: 'address', type: 'address', indexed: true },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        { name: 'data', internalType: 'bytes', type: 'bytes', indexed: false },
        {
          name: 'operatorData',
          internalType: 'bytes',
          type: 'bytes',
          indexed: false,
        },
      ],
      name: 'Minted',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'tokenHolder',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'RevokedOperator',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'from', internalType: 'address', type: 'address', indexed: true },
        { name: 'to', internalType: 'address', type: 'address', indexed: true },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        { name: 'data', internalType: 'bytes', type: 'bytes', indexed: false },
        {
          name: 'operatorData',
          internalType: 'bytes',
          type: 'bytes',
          indexed: false,
        },
      ],
      name: 'Sent',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'TokenDowngraded',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'TokenUpgraded',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'from', internalType: 'address', type: 'address', indexed: true },
        { name: 'to', internalType: 'address', type: 'address', indexed: true },
        {
          name: 'value',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Transfer',
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'spender', internalType: 'address', type: 'address' },
      ],
      name: 'allowance',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'approve',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [{ name: 'operator', internalType: 'address', type: 'address' }],
      name: 'authorizeOperator',
      outputs: [],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
      name: 'balanceOf',
      outputs: [{ name: 'balance', internalType: 'uint256', type: 'uint256' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'burn',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [],
      name: 'castrate',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'id', internalType: 'bytes32', type: 'bytes32' },
        { name: 'data', internalType: 'bytes32[]', type: 'bytes32[]' },
      ],
      name: 'createAgreement',
      outputs: [],
    },
    {
      stateMutability: 'pure',
      type: 'function',
      inputs: [],
      name: 'decimals',
      outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'subtractedValue', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'decreaseAllowance',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [],
      name: 'defaultOperators',
      outputs: [{ name: '', internalType: 'address[]', type: 'address[]' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
      name: 'downgrade',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'to', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'downgradeTo',
      outputs: [],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
      name: 'getAccountActiveAgreements',
      outputs: [
        {
          name: '',
          internalType: 'contract ISuperAgreement[]',
          type: 'address[]',
        },
      ],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [
        { name: 'agreementClass', internalType: 'address', type: 'address' },
        { name: 'id', internalType: 'bytes32', type: 'bytes32' },
        { name: 'dataLength', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'getAgreementData',
      outputs: [{ name: 'data', internalType: 'bytes32[]', type: 'bytes32[]' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [
        { name: 'agreementClass', internalType: 'address', type: 'address' },
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'slotId', internalType: 'uint256', type: 'uint256' },
        { name: 'dataLength', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'getAgreementStateSlot',
      outputs: [
        { name: 'slotData', internalType: 'bytes32[]', type: 'bytes32[]' },
      ],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [],
      name: 'getCodeAddress',
      outputs: [
        { name: 'codeAddress', internalType: 'address', type: 'address' },
      ],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [],
      name: 'getHost',
      outputs: [{ name: 'host', internalType: 'address', type: 'address' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [],
      name: 'getUnderlyingToken',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
    },
    {
      stateMutability: 'pure',
      type: 'function',
      inputs: [],
      name: 'granularity',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'addedValue', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'increaseAllowance',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        {
          name: 'underlyingToken',
          internalType: 'contract IERC20',
          type: 'address',
        },
        { name: 'underlyingDecimals', internalType: 'uint8', type: 'uint8' },
        { name: 'n', internalType: 'string', type: 'string' },
        { name: 's', internalType: 'string', type: 'string' },
      ],
      name: 'initialize',
      outputs: [],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'timestamp', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'isAccountCritical',
      outputs: [{ name: 'isCritical', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
      name: 'isAccountCriticalNow',
      outputs: [{ name: 'isCritical', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'timestamp', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'isAccountSolvent',
      outputs: [{ name: 'isSolvent', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
      name: 'isAccountSolventNow',
      outputs: [{ name: 'isSolvent', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [
        { name: 'operator', internalType: 'address', type: 'address' },
        { name: 'tokenHolder', internalType: 'address', type: 'address' },
      ],
      name: 'isOperatorFor',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'id', internalType: 'bytes32', type: 'bytes32' },
        { name: 'liquidationTypeData', internalType: 'bytes', type: 'bytes' },
        { name: 'liquidatorAccount', internalType: 'address', type: 'address' },
        { name: 'useDefaultRewardAccount', internalType: 'bool', type: 'bool' },
        { name: 'targetAccount', internalType: 'address', type: 'address' },
        { name: 'rewardAmount', internalType: 'uint256', type: 'uint256' },
        {
          name: 'targetAccountBalanceDelta',
          internalType: 'int256',
          type: 'int256',
        },
      ],
      name: 'makeLiquidationPayoutsV2',
      outputs: [],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [],
      name: 'name',
      outputs: [{ name: '', internalType: 'string', type: 'string' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'operationApprove',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'subtractedValue', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'operationDecreaseAllowance',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'operationDowngrade',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'addedValue', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'operationIncreaseAllowance',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'recipient', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'userData', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'operationSend',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'recipient', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'operationTransferFrom',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'operationUpgrade',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
        { name: 'operatorData', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'operatorBurn',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'sender', internalType: 'address', type: 'address' },
        { name: 'recipient', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
        { name: 'operatorData', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'operatorSend',
      outputs: [],
    },
    {
      stateMutability: 'pure',
      type: 'function',
      inputs: [],
      name: 'proxiableUUID',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'timestamp', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'realtimeBalanceOf',
      outputs: [
        { name: 'availableBalance', internalType: 'int256', type: 'int256' },
        { name: 'deposit', internalType: 'uint256', type: 'uint256' },
        { name: 'owedDeposit', internalType: 'uint256', type: 'uint256' },
      ],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
      name: 'realtimeBalanceOfNow',
      outputs: [
        { name: 'availableBalance', internalType: 'int256', type: 'int256' },
        { name: 'deposit', internalType: 'uint256', type: 'uint256' },
        { name: 'owedDeposit', internalType: 'uint256', type: 'uint256' },
        { name: 'timestamp', internalType: 'uint256', type: 'uint256' },
      ],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [{ name: 'operator', internalType: 'address', type: 'address' }],
      name: 'revokeOperator',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'selfApproveFor',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'userData', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'selfBurn',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'userData', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'selfMint',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'holder', internalType: 'address', type: 'address' },
        { name: 'spender', internalType: 'address', type: 'address' },
        { name: 'recipient', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'selfTransferFrom',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'recipient', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'send',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'delta', internalType: 'int256', type: 'int256' },
      ],
      name: 'settleBalance',
      outputs: [],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [],
      name: 'symbol',
      outputs: [{ name: '', internalType: 'string', type: 'string' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'id', internalType: 'bytes32', type: 'bytes32' },
        { name: 'dataLength', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'terminateAgreement',
      outputs: [],
    },
    {
      stateMutability: 'view',
      type: 'function',
      inputs: [],
      name: 'totalSupply',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'recipient', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'transfer',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [{ name: 'recipient', internalType: 'address', type: 'address' }],
      name: 'transferAll',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'holder', internalType: 'address', type: 'address' },
        { name: 'recipient', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'transferFrom',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'id', internalType: 'bytes32', type: 'bytes32' },
        { name: 'data', internalType: 'bytes32[]', type: 'bytes32[]' },
      ],
      name: 'updateAgreementData',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'slotId', internalType: 'uint256', type: 'uint256' },
        { name: 'slotData', internalType: 'bytes32[]', type: 'bytes32[]' },
      ],
      name: 'updateAgreementStateSlot',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [{ name: 'newAddress', internalType: 'address', type: 'address' }],
      name: 'updateCode',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
      name: 'upgrade',
      outputs: [],
    },
    {
      stateMutability: 'nonpayable',
      type: 'function',
      inputs: [
        { name: 'to', internalType: 'address', type: 'address' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'upgradeTo',
      outputs: [],
    },
  ] as const