import Button from "@/components/Button/Button";
import Footer from "@/components/Footer/Footer";
import Modal from "@/components/BookModal/Modal/Modal";
import PricingCard from "@/components/PricingCard/PricingCard";
import styles from "@/styles/Home.module.css";

import Head from "next/head";
import { useState } from "react";
import BookModal from "@/components/BookModal/BookModal";

export default function Home() {
  const [showModal, setShowModal] = useState(false);

  const openModal = () => setShowModal(true);
  const closeModal = () => setShowModal(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.Main}>
        <header className={styles.Header}>
          <img src="/logo.svg" />
        </header>

        <div className={styles.Wrapper}>
          <section>
            <div className={styles.Heading}>
              <h1>Choose a pricing plan</h1>
              <p>Build and scale your app easier than ever before.</p>
            </div>
            <div className={styles.PricingOptions}>
              <PricingCard
                title="Starter"
                description="Up to 1,000,000 compute units/mo"
                ctaTitle="Subscribe"
                price={29}
                onFinish={openModal}
                features={[
                  "Supernode, Build, Monitor, and Notify",
                  "Enhanced APIs",
                  "Multichain mainnets and testnets",
                  "No daily request limits",
                  "Full archive data",
                ]}
              />

              <PricingCard
                title="Growth"
                description="Up to 5,000,000 compute units/mo"
                ctaTitle="Subscribe"
                price={99}
                onFinish={openModal}
                features={[
                  "Auto-scaling compute units",
                  "Parity trace and gETH debug",
                  "Access to reinforced transactions",
                  "Early access t2x higher throughput",
                  "Access to Paymaster Services",
                ]}
              />

              <PricingCard
                outlined
                title="Business"
                description="Custom compute units"
                ctaTitle="Talk to us"
                price={1000}
                onClick={openModal}
                features={[
                  "Uncapped Simulation Throughput",
                  "Committed use discounts",
                  "Custom SLAs",
                  "Custom throughput",
                  "24/7 VIP support",
                ]}
              />
            </div>
          </section>

          <BookModal show={showModal} onClose={closeModal} />
          <Footer />
        </div>
      </main>
    </>
  );
}
